[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
common = { path = "../common" }
rustyline = "15.0.0"
rustyline-derive = "0.11.0"
colored = "2.2.0"
